# Build Docker image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Develop'
  appName: 'bs-flex-api'  # Build.Repository.Name ?
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

steps:
- task: Docker@1
  displayName: 'Build image (self-service)'
  inputs:
    imageName: '$(appName):$(Build.SourceBranchName)'
- task: Docker@1
  displayName: Login
  inputs:
    azureSubscriptionEndpoint: 'Lias Online Dev'
    azureContainerRegistry: liasomniadevakscicdmvpacr.azurecr.io
    command: login
- task: Docker@1
  displayName: 'Push image (self-service)'
  inputs:
    command: 'push'
    imageName: '$(appName):$(Build.SourceBranchName)'
